# -*- coding: utf-8 -*-
"""
Sign Language A-Z  --  Live Webcam Prediction + Text-to-Speech
===============================================================
Uses MediaPipe Hands + the trained MLP model to recognise
ASL alphabet signs (A-Z) from your webcam in real time,
with integrated pyttsx3 text-to-speech output.

Temporal Logic (prevents duplicate letters):
  - 20-frame majority voting (>80% consistency required)
  - 90% model confidence threshold
  - 0.5-second hold timer before committing a letter
  - Hand-reset lock: must remove hand or show a different sign
    before the same letter can be added again

Text-to-Speech:
  - pyttsx3 engine (singleton, non-blocking via background thread)
  - ENTER speaks the full sentence buffer
  - Duplicate speech protection while TTS is active
  - Real-time status display: READY / SPEAKING / COMPLETED
  - AUTO_CLEAR option to clear sentence after speaking

Bilingual Support (English / Tamil):
  - L key toggles between English and Tamil modes
  - Tamil mode: translates recognised text and displays in Tamil
  - Tamil TTS voice selection (falls back to English if unavailable)
  - Future-ready architecture: add Hindi, Telugu, Malayalam, etc.

Controls:
  Q / ESC   -> Quit
  C         -> Clear word buffer AND sentence buffer
  L         -> Toggle language (English <-> Tamil)
  SPACE     -> Finish current word, push to sentence buffer
  BKSP      -> Delete last character from word buffer
  ENTER     -> Speak the accumulated sentence aloud

Requirements:
  - models/mlp_model.pkl
  - models/label_encoder.pkl
  - models/scaler.pkl
  (Generated by train_mlp.py)
  - pyttsx3  (pip install pyttsx3)
  - Pillow   (pip install Pillow, optional for Tamil text display)
"""

# ── Suppress noisy logs ────────────────────────────────────────────────────
import os, warnings, logging

os.environ["GLOG_minloglevel"] = "3"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
warnings.filterwarnings("ignore")
logging.getLogger("httpx").setLevel(logging.WARNING)

# ── Monkeypatch httpcore for googletrans compatibility ──────────────────────
import httpcore
if not hasattr(httpcore, "SyncHTTPTransport"):
    class DummySyncHTTPTransport:
        pass
    httpcore.SyncHTTPTransport = DummySyncHTTPTransport

# ── Imports ─────────────────────────────────────────────────────────────────
import sys
import time
import functools
import threading
import numpy as np
import cv2
import mediapipe as mp
import joblib
import pyttsx3
import pythoncom
from collections import deque, Counter
from supabase_client import SupabaseManager
from utils import extract_enhanced_features  # Enhanced landmarks and engineered features
from emotion_detection import EmotionDetector

# ── Optional: PIL for Unicode (Tamil) text rendering ────────────────────
try:
    from PIL import Image, ImageDraw, ImageFont
    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False
    print("[WARN] PIL/Pillow not installed. Tamil text display will use fallback.")
    print("       Install with: pip install Pillow")

# ── Paths ───────────────────────────────────────────────────────────────────
MODEL_PATH = os.path.join("models", "mlp_model.pkl")
ENCODER_PATH = os.path.join("models", "label_encoder.pkl")
SCALER_PATH = os.path.join("models", "scaler.pkl")

# Compatibility / Feature mode indicator
MODEL_EXPECTS_ENHANCED = False

# ── MediaPipe Hand Tracking Configuration ──────────────────────────────────
# static_image_mode=False: enables tracking mode — faster because it reuses
#   previous frame landmarks instead of running full detection every frame.
MP_STATIC_IMAGE_MODE = False

# max_num_hands=1: restricts to single hand — reduces computation and prevents
#   the detector from splitting attention between hands.
MP_MAX_NUM_HANDS = 1

# min_detection_confidence=0.70: lower threshold keeps the fast tracking path active
#   more often, avoiding expensive full-frame re-detection. Tradeoff: speed > strictness.
MP_MIN_DETECTION_CONFIDENCE = 0.70

# min_tracking_confidence=0.70: lower threshold maintains tracking continuity,
#   preventing frequent re-detection that adds latency. Tradeoff: speed > strictness.
MP_MIN_TRACKING_CONFIDENCE = 0.70

# ── Adaptive EMA Landmark Smoothing Configuration ───────────────────────────
# Motion-adaptive smoothing: low alpha = more smoothing, high alpha = more responsive.
# When hand is stationary → alpha_slow (stable, reduces jitter)
# When hand moves quickly  → alpha_fast (near-raw, eliminates lag)
EMA_ALPHA_SLOW = 0.4          # Smoothing alpha when hand is stationary
EMA_ALPHA_FAST = 0.9          # Smoothing alpha when hand moves fast
EMA_SPEED_THRESHOLD = 0.01    # Landmark displacement threshold for fast mode

# ── Hysteresis Configuration ───────────────────────────────────────────────
# HAND_MISSING_GRACE_FRAMES=5: continue displaying last valid landmarks for
#   up to 5 frames after MediaPipe loses detection. Prevents flickering.
HAND_MISSING_GRACE_FRAMES = 5

# ── Emotion Detection Throttle ─────────────────────────────────────────────
# EMOTION_DETECT_INTERVAL=30: only send frames to emotion detector every 30 frames.
EMOTION_DETECT_INTERVAL = 30

# ── Webcam Resolution ──────────────────────────────────────────────────────
WEBCAM_WIDTH = 640
WEBCAM_HEIGHT = 480

# ── Motion Detection ───────────────────────────────────────────────────────
# MOTION_THRESHOLD=0.015: average inter-frame landmark displacement above this
#   value indicates the hand is moving. Pauses prediction to avoid noise.
MOTION_THRESHOLD = 0.015

# ── Hand Quality Thresholds ────────────────────────────────────────────────
HAND_EDGE_MARGIN = 0.02          # 2% margin from frame edges
HAND_MIN_BBOX_SIZE = 0.12        # minimum bounding box dimension (12% of frame)
HAND_MIN_LANDMARK_SPREAD = 0.02   # minimum std-dev of landmark positions
STABILITY_BUFFER_SIZE = 10
STABILITY_MAX_VARIANCE = 0.005

# ── Temporal Logic Configuration ────────────────────────────────────────────
HISTORY_SIZE = 10             # Number of frames for majority voting (reduced from 30 for responsiveness)
CONSISTENCY_THRESHOLD = 0.80  # >80% of history must agree for a "stable" prediction
CONFIDENCE_THRESHOLD = 0.90   # Model confidence must exceed 90%
HOLD_TIME_REQUIRED = 0.5      # Seconds the prediction must be held before committing
FEEDBACK_DISPLAY_DURATION = 1.0  # Seconds to show "Added X" confirmation

# ── TTS Configuration ──────────────────────────────────────────────────────
TTS_SPEECH_RATE = 150         # Words per minute
TTS_VOLUME = 1.0              # 0.0 to 1.0
AUTO_CLEAR = True             # Clear sentence buffer automatically after speaking

# ── Colours (BGR) ───────────────────────────────────────────────────────────
BG_DARK = (30, 20, 20)            # Deep obsidian slate (semi-transparent)
BORDER_COLOR = (120, 40, 90)      # Neon dark purple outline
ACCENT_COLOR = (208, 194, 0)      # Neon Cyan/Teal accent
TEAL = (208, 194, 0)              # Neon Cyan
TEAL_LIGHT = (230, 220, 100)      # Light Cyan
WHITE = (255, 255, 255)
GREEN = (100, 255, 100)           # Cyber lime green
RED = (80, 80, 255)               # Warning red
YELLOW = (60, 220, 255)           # Alert orange/yellow
GRAY = (140, 140, 140)
ORANGE = (30, 140, 255)           # Electric orange
CYAN = (255, 255, 0)
PURPLE = (220, 80, 220)           # Tech purple


# ═══════════════════════════════════════════════════════════════════════════
# Language Configuration (future-ready: add new languages here)
# ═══════════════════════════════════════════════════════════════════════════

LANGUAGE_CONFIG = {
    "English": {"code": "en", "name_en": "English", "name_native": "English"},
    "Tamil": {"code": "ta", "name_en": "Tamil", "name_native": "தமிழ்"},
}

AVAILABLE_LANGUAGES = list(LANGUAGE_CONFIG.keys())

# ── Emergency Configuration ──────────────────────────────────────────────────
EMERGENCY_KEYWORDS = {
    "English": ["HELP", "EMERGENCY", "DOCTOR", "AMBULANCE", "MEDICINE", "HOSPITAL", "PAIN", "ACCIDENT", "DANGER", "FIRE"],
    "Tamil": ["உதவி", "அவசரம்", "மருத்துவர்", "ஆம்புலன்ஸ்", "மருத்துவமனை", "வலி", "விபத்து", "ஆபத்து", "தீ"]
}

def is_emergency_text(text: str) -> str | None:
    """
    Checks if text (case-insensitive) contains any of the emergency keywords.
    Returns the matched keyword if found, otherwise None.
    """
    if not text:
        return None
    
    # Check English keywords (tokenized comparison)
    tokens = [t.upper().strip() for t in text.split()]
    for kw in EMERGENCY_KEYWORDS["English"]:
        if kw in tokens:
            return kw

    # Check Tamil keywords (direct substring match is safer because of word builders)
    for kw in EMERGENCY_KEYWORDS["Tamil"]:
        if kw in text:
            return kw

    return None


TRANSLATION_DICT = {
    "Tamil": {
        "HELLO": "வணக்கம்",
        "THANK YOU": "நன்றி",
        "PLEASE": "தயவுசெய்து",
        "YES": "ஆம்",
        "NO": "இல்லை",
        "GOODBYE": "போய் வருகிறேன்",
        "SORRY": "மன்னிக்கவும்",
        "HELP": "உதவி",
        "I LOVE YOU": "நான் உன்னை காதலிக்கிறேன்",
        "GOOD MORNING": "காலை வணக்கம்",
        "GOOD NIGHT": "இரவு வணக்கம்",
        "WELCOME": "வரவேற்கிறோம்",
        "HOW ARE YOU": "நீங்கள் எப்படி இருக்கிறீர்கள்",
        "FINE": "நலம்",
        "MY NAME IS": "என் பெயர்",
        "WHAT": "என்ன",
        "WHY": "ஏன்",
        "WHEN": "எப்போது",
        "WHERE": "எங்கே",
        "WHO": "யார்",
        "HOW": "எப்படி",
        "MY": "என்",
        "YOUR": "உங்கள்",
        "NAME": "பெயர்",
        "FATHER": "அப்பா",
        "MOTHER": "அம்மா",
        "BROTHER": "சகோதரர்",
        "SISTER": "சகோதரி",
        "FRIEND": "நண்பர்",
        "WATER": "தண்ணீர்",
        "FOOD": "உணவு",
        "HOUSE": "வீடு",
        "SCHOOL": "பள்ளி",
        "BOOK": "புத்தகம்",
        "PEN": "பேனா",
        "OK": "சரி",
        "STOP": "நிறுத்து",
        "GO": "செல்",
        "COME": "வா",
        "SIT": "உட்கார்",
        "STAND": "எழுந்திரு",
        "EAT": "சாப்பிடு",
        "DRINK": "குடி",
        "SLEEP": "தூங்கு",
        "LOVE": "அன்பு",
        "HAPPY": "மகிழ்ச்சி",
        "SAD": "சோகம்",
        "BIG": "பெரிய",
        "SMALL": "சிறிய",
        "HOT": "சூடான",
        "COLD": "குளிர்",
        "HI": "வணக்கம்"
    }
}


# ── Tamil Phonetic Transliteration Dictionary (Fallback for missing Tamil TTS voice) ────
TAMIL_PHONETIC_DICT = {
    "வணக்கம்": "vanakkam",
    "நன்றி": "nandri",
    "தயவுசெய்து": "dhayavu seidhu",
    "ஆம்": "aamaam",
    "இல்லை": "illai",
    "போய் வருகிறேன்": "poi varugiren",
    "மன்னிக்கவும்": "mannikkavum",
    "உதவி": "udhavi",
    "நான் உன்னை காதலிக்கிறேன்": "naan unnai kaadhalikkiren",
    "காலை வணக்கம்": "kaalai vanakkam",
    "இரவு வணக்கம்": "iravu vanakkam",
    "வரவேற்கிறோம்": "varaverkirom",
    "நீங்கள் எப்படி இருக்கிறீர்கள்": "neenga eppadi irukeenga",
    "நலம்": "nalam",
    "என் பெயர்": "en peyar",
    "என்ன": "enna",
    "ஏன்": "aen",
    "எப்போது": "eppodhu",
    "எங்கே": "engae",
    "யார்": "yaar",
    "எப்படி": "eppadi",
    "என்": "en",
    "உங்கள்": "ungal",
    "பெயர்": "peyar",
    "அப்பா": "appa",
    "அம்மா": "amma",
    "சகோதரர்": "sagodharar",
    "சகோதரி": "sagodhiri",
    "நண்பர்": "nanbar",
    "தண்ணீர்": "thanneer",
    "உணவு": "unavu",
    "வீடு": "veedu",
    "பள்ளி": "palli",
    "புத்தகம்": "puthagam",
    "பேனா": "pena",
    "சரி": "sari",
    "நிறுத்து": "niruthu",
    "செல்": "sel",
    "வா": "vaa",
    "உட்கார்": "utkaar",
    "எழுந்திரு": "ezhundhiru",
    "சாப்பிடு": "saapidu",
    "குடி": "kudi",
    "தூங்கு": "thoongu",
    "அன்பு": "anbu",
    "மகிழ்ச்சி": "magizhchi",
    "சோகம்": "sogam",
    "பெரிய": "periya",
    "சிறிய": "siriya",
    "சூடான": "soodana",
    "குளிர்": "kulir",
    "அவசர உதவி கோரப்பட்டுள்ளது": "avasara udhavi khorappattulladhu",
}

def transliterate_tamil_text(text: str) -> str:
    """
    Transliterates Tamil Unicode text into Romanized phonetic English fallback
    so that default English TTS voices can read them audibly.
    """
    if not text:
        return text
        
    cleaned = text.strip()
    # Check direct match
    if cleaned in TAMIL_PHONETIC_DICT:
        return TAMIL_PHONETIC_DICT[cleaned]
        
    # Split text into words/phrases and check
    words = cleaned.split()
    romanized_words = []
    for word in words:
        stripped = word.strip(".,!?\"'()[]{}")
        if stripped in TAMIL_PHONETIC_DICT:
            romanized_words.append(TAMIL_PHONETIC_DICT[stripped])
        else:
            # Find if this Tamil word corresponds to any English word in our translation dict
            found_eng = None
            for eng_k, tamil_v in TRANSLATION_DICT.get("Tamil", {}).items():
                if tamil_v == stripped:
                    found_eng = eng_k
                    break
            if found_eng:
                # Use phonetic version of the English word or just the English word itself
                romanized_words.append(found_eng.lower())
            else:
                pass
                
    if romanized_words:
        return " ".join(romanized_words)
    return ""


# ── Global Translator & Cache for Real-Time Translation ──────────────────────
_google_translator = None
_translation_cache = {}

def translate_to_tamil(text: str) -> str:
    """
    Translates English text to Tamil using googletrans==4.0.0rc1.
    Utilizes local dictionary mapping first, then memory cache, and finally 
    falls back to the googletrans API to prevent UI freezing and API limit issues.
    """
    global _google_translator
    if not text or not text.strip():
        return text

    cleaned_text = text.strip()
    upper_text = cleaned_text.upper()

    # 1. Try local dictionary lookup first (instant & offline-friendly)
    lang_dict = TRANSLATION_DICT.get("Tamil", {})
    if upper_text in lang_dict:
        return lang_dict[upper_text]

    # 2. Check memory cache for previous translations
    if cleaned_text in _translation_cache:
        return _translation_cache[cleaned_text]

    # 3. Call googletrans API
    try:
        if _google_translator is None:
            from googletrans import Translator
            _google_translator = Translator()
        
        result = _google_translator.translate(cleaned_text, src='en', dest='ta')
        if result and result.text:
            _translation_cache[cleaned_text] = result.text
            return result.text
        else:
            print("[ERROR] Tamil Translation Failed")
    except Exception as e:
        print(f"[ERROR] Tamil Translation Failed: {e}")

    # Cache original text on failure to prevent spamming the API on every frame
    _translation_cache[cleaned_text] = text
    return text


# ═══════════════════════════════════════════════════════════════════════════
# Translation Engine (modular design for multilingual support)
# ═══════════════════════════════════════════════════════════════════════════

class TranslationEngine:
    """
    Modular translation engine supporting English → target language.

    Currently uses googletrans-based translation for Tamil with local dictionary backup.
    Designed to seamlessly integrate API-based translation (Google Translate,
    DeepL, etc.) without refactoring the calling code.

    Usage:
        translator = TranslationEngine(target_lang="Tamil")
        text = translator.translate("HELLO")  # → "வணக்கம்"

    To add a new language:
        1. Add entry to LANGUAGE_CONFIG
        2. Add translations to TRANSLATION_DICT
        3. (Optional) Implement API-based fallback in _api_translate()
    """

    def __init__(self, target_lang="English"):
        self.target_lang = target_lang

    @property
    def is_active(self):
        return self.target_lang != "English"

    def translate(self, text: str) -> str:
        if not self.is_active or not text:
            return text

        if self.target_lang == "Tamil":
            return translate_to_tamil(text)

        lang_dict = TRANSLATION_DICT.get(self.target_lang, {})
        upper_text = text.upper().strip()

        # 1. Try full-phrase match
        if upper_text in lang_dict:
            return lang_dict[upper_text]

        # 2. Try word-by-word translation
        words = upper_text.split()
        translated_words = []
        for word in words:
            if word in lang_dict:
                translated_words.append(lang_dict[word])
            else:
                translated_words.append(word)

        result = " ".join(translated_words)

        # 3. If no dictionary match at all, try API (fallback)
        if result == upper_text and upper_text:
            result = self._api_translate(text)

        return result

    def _api_translate(self, text: str) -> str:
        """
        Translates text using Google Translate via deep-translator.
        Falls back to original text if offline or if an error occurs.
        """
        try:
            from deep_translator import GoogleTranslator
            target_code = LANGUAGE_CONFIG.get(self.target_lang, {}).get("code", "en")
            return GoogleTranslator(source='en', target=target_code).translate(text)
        except Exception as e:
            print(f"[WARN] Translation failed (offline or API error): {e}")
            return text



# ═══════════════════════════════════════════════════════════════════════════
# Speech Engine (persistent worker thread + queue architecture)
# ═══════════════════════════════════════════════════════════════════════════

import queue  # stdlib, for thread-safe speech request passing


class SpeechEngine:
    """
    Production-grade TTS wrapper using pyttsx3.

    Architecture:
      Main Thread -> speak(text) -> Queue.put(text)
      Worker Thread -> Queue.get() -> engine.say() -> engine.runAndWait()

    Features:
      - Engine is created once and kept alive for the lifetime of the application.
      - Supports non-blocking speech with simple thread-safe queue.
      - Prevents overlapping speech requests.
      - Logs diagnostic properties (Worker Alive, Queue Size, Current Status, is_speaking).
    """

    _instance = None
    _init_lock = threading.Lock()

    # Speech status constants
    STATUS_READY = "READY"
    STATUS_SPEAKING = "SPEAKING"
    STATUS_COMPLETED = "COMPLETED"

    def __new__(cls):
        """Singleton: ensure only one SpeechEngine instance exists."""
        with cls._init_lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._initialized = False
            return cls._instance

    def __init__(self):
        """Initialize the speech engine interface (runs only once)."""
        if self._initialized:
            return
        self._initialized = True

        # Thread-safe state tracking
        self._status_lock = threading.Lock()
        self._status = self.STATUS_READY
        self._is_speaking_val = False
        self._just_completed_flag = False
        self._current_text = ""
        self._completed_timestamp = 0.0
        self._completed_display_duration = 2.0  # Show COMPLETED for 2s
        self._auto_cleared = False  # One-shot flag for auto-clear

        # Queue and shutdown signal
        self._queue = queue.Queue()
        self._shutdown_event = threading.Event()

        # Engine-available flag for compatibility
        self._engine_ready = threading.Event()

        # Launch persistent worker thread
        self._worker_thread = threading.Thread(
            target=self._worker_loop,
            name="SpeechWorkerThread",
            daemon=True
        )
        self._worker_thread.start()

        print("[OK] TTS persistent speech engine initialized.")

    def _worker_loop(self):
        """Persistent background worker loop that handles pyttsx3 commands."""
        import pythoncom
        pythoncom.CoInitialize()
        engine = None
        try:
            print("[DEBUG] Engine Created (Single Instance)")
            engine = pyttsx3.init()
            engine.setProperty("rate", TTS_SPEECH_RATE)
            engine.setProperty("volume", TTS_VOLUME)
            self._engine_ready.set()
        except Exception as e:
            print(f"[ERROR] Failed to initialize pyttsx3 engine: {e}")
            pythoncom.CoUninitialize()
            return

        while not self._shutdown_event.is_set():
            try:
                # Non-blocking fetch with 100ms timeout
                request = self._queue.get(timeout=0.1)
            except queue.Empty:
                continue

            # Unpack request safely for backward compatibility
            req_data = request
            if len(req_data) == 4:
                text, language, volume, english_fallback = req_data
            else:
                text, language, volume = req_data
                english_fallback = ""

            # Update state to SPEAKING
            with self._status_lock:
                self._is_speaking_val = True
                self._status = self.STATUS_SPEAKING
                self._current_text = text
                self._auto_cleared = False

            # Diagnostic logs after every request received
            worker_alive = self._worker_thread.is_alive()
            print(f"[DEBUG TTS] Worker Alive: {worker_alive} | Queue Size: {self._queue.qsize()} | Status: {self._status} | is_speaking: {self._is_speaking_val}")

            # Verify Tamil text reaches the speech engine
            try:
                print(f"[DEBUG] Language: {language}")
                print(f"[DEBUG] Text To Speak: {text}")
            except Exception:
                try:
                    print(f"[DEBUG] Language: {language}")
                    print(f"[DEBUG] Text To Speak: {text.encode('utf-8', errors='replace')}")
                except Exception:
                    pass

            try:
                # Set dynamic volume override
                engine.setProperty("volume", volume if volume is not None else TTS_VOLUME)

                # Attempt Tamil voice selection if requested
                if language == "Tamil":
                    tamil_tts_success = False
                    temp_file_path = "temp.mp3"

                    # 1. Attempt Tamil Audio Generation using gTTS
                    try:
                        from gtts import gTTS
                        tts_obj = gTTS(text=text, lang="ta")
                        tts_obj.save(temp_file_path)
                    except Exception as e:
                        print(f"[ERROR] Tamil Audio Generation Failed: {e}")

                    # 2. Attempt Playback using pygame
                    if os.path.exists(temp_file_path):
                        try:
                            import pygame
                            if not pygame.mixer.get_init():
                                pygame.mixer.init()
                            pygame.mixer.music.load(temp_file_path)
                            print("[DEBUG] Speech Started")
                            pygame.mixer.music.play()
                            while pygame.mixer.music.get_busy():
                                time.sleep(0.05)
                            pygame.mixer.music.stop()
                            try:
                                pygame.mixer.music.unload()
                            except Exception:
                                pass
                            pygame.mixer.quit()
                            print("[DEBUG] Speech Finished")
                            tamil_tts_success = True
                        except Exception as e:
                            print(f"[ERROR] Tamil Playback Failed: {e}")
                        finally:
                            # Wait for audio playback to finish before deleting temp.mp3
                            for _ in range(5):
                                try:
                                    if os.path.exists(temp_file_path):
                                        os.remove(temp_file_path)
                                    break
                                except Exception:
                                    time.sleep(0.1)

                    # 3. Fallback: Speak transliterated Tamil using English voice if gTTS/pygame failed
                    if not tamil_tts_success:
                        print("[TTS] Tamil TTS failed. Falling back to phonetic transliteration...")
                        phonetic_text = transliterate_tamil_text(text)
                        if phonetic_text and phonetic_text.strip():
                            fallback_text = phonetic_text
                            print(f"[TTS] Using phonetic Tamil transliteration: {fallback_text}")
                        elif english_fallback and english_fallback.strip():
                            fallback_text = english_fallback
                            print(f"[TTS] Transliteration empty. Using English fallback: {fallback_text}")
                        else:
                            fallback_text = text
                            print("[TTS] Transliteration empty and no English fallback. Playing original Tamil.")

                        # Reset voice to default English
                        try:
                            voices = engine.getProperty("voices")
                            for voice in voices:
                                voice_name = voice.name.lower() if hasattr(voice, 'name') else ""
                                if 'tamil' not in voice_name:
                                    engine.setProperty("voice", voice.id)
                                    break
                        except Exception:
                            pass

                        print("[DEBUG] Speech Started")
                        engine.say(fallback_text)
                        engine.runAndWait()
                        print("[DEBUG] Speech Finished")

                else:
                    # Reset voice to default English
                    try:
                        voices = engine.getProperty("voices")
                        for voice in voices:
                            voice_name = voice.name.lower() if hasattr(voice, 'name') else ""
                            if 'tamil' not in voice_name:
                                engine.setProperty("voice", voice.id)
                                break
                    except Exception:
                        pass

                    print("[DEBUG] Speech Started")
                    engine.say(text)
                    engine.runAndWait()
                    print("[DEBUG] Speech Finished")

            except Exception as e:
                print(f"[ERROR] Exception during speech execution: {e}")
            finally:
                self._queue.task_done()

                # Reset speaking state to COMPLETED
                with self._status_lock:
                    self._is_speaking_val = False
                    self._status = self.STATUS_COMPLETED
                    self._completed_timestamp = time.time()
                    self._just_completed_flag = True
                print("[DEBUG] Status Reset")

                # Diagnostic logs after request processed
                worker_alive = self._worker_thread.is_alive()
                print(f"[DEBUG TTS] Worker Alive: {worker_alive} | Queue Size: {self._queue.qsize()} | Status: {self.status} | is_speaking: {self.is_speaking}")

        # Shutdown cleanup
        if engine is not None:
            try:
                engine.stop()
            except Exception:
                pass
            del engine
            print("[DEBUG] Engine Destroyed")

        pythoncom.CoUninitialize()

    # ── Public API (called from the main/UI thread) ─────────────────────

    @property
    def status(self) -> str:
        """Current speech status: READY, SPEAKING, or COMPLETED."""
        with self._status_lock:
            # Auto-transition COMPLETED → READY after the display duration
            if (self._status == self.STATUS_COMPLETED
                    and time.time() - self._completed_timestamp
                    > self._completed_display_duration):
                self._status = self.STATUS_READY
            return self._status

    @property
    def is_speaking(self) -> bool:
        """True if TTS is currently producing audio."""
        with self._status_lock:
            return self._is_speaking_val

    @property
    def just_completed(self) -> bool:
        """
        True ONCE after speech finishes, for triggering auto-clear.
        Calling this consumes the flag (one-shot).
        """
        with self._status_lock:
            if self._just_completed_flag:
                self._just_completed_flag = False
                return True
            return False

    def speak(self, text: str, language: str = "English", volume: float = None, english_fallback: str = "") -> bool:
        """
        Queue a speech request to be processed by the background worker thread.

        Args:
            text: The text to speak.
            language: Language for TTS voice selection ("English" or "Tamil").
            volume: Volume level override (0.0 to 1.0).
            english_fallback: English equivalent to speak if target language TTS is unavailable.

        Returns True if the request was accepted (queued), False if rejected (empty text).
        """
        print("[DEBUG] speak() called")
        if not text or not text.strip():
            print("[TTS] No text to speak.")
            return False

        clean_text = text.strip()

        # Push to the thread-safe queue
        self._queue.put((clean_text, language, volume, english_fallback))
        print("[DEBUG] Queue Accepted")
        
        # Diagnostic logs on the main thread after queuing
        worker_alive = self._worker_thread.is_alive()
        print(f"[DEBUG TTS] Queue Size: {self._queue.qsize()} | Worker Alive: {worker_alive} | Status: {self.status} | is_speaking: {self.is_speaking}")
        return True

    def shutdown(self):
        """Set shutdown signal to clean up thread on exit."""
        self._shutdown_event.set()
        if self._worker_thread.is_alive():
            self._worker_thread.join(timeout=1.0)



def save_recognition(recognized_text: str, translated_text: str = "",
                     selected_language: str = "English", confidence: float = 100.0) -> bool:
    """
    Saves the recognized text, translation, language, confidence, and timestamp to Supabase.
    """
    try:
        from datetime import datetime, timezone
        timestamp = datetime.now(timezone.utc).isoformat()
        
        sb = SupabaseManager()
        
        data = {
            "recognized_text": recognized_text,
            "translated_text": translated_text,
            "selected_language": selected_language,
            "confidence": confidence,
            "created_at": timestamp
        }
        
        res = sb.insert("recognition_history", data)
        if res is not None:
            print("[DB] Saved Successfully")
            return True
        else:
            print("[DB] Save Failed")
            return False
            
    except Exception as e:
        print("[DB] Save Failed")
        print(f"     Error: {e}")
        return False


def get_recent_history() -> list | None:
    """
    Fetches the latest 20 records from recognition_history table.
    """
    try:
        sb = SupabaseManager()
        res = sb.client.table("recognition_history").select("*").order("created_at", descending=True).limit(20).execute()
        return res.data
    except Exception as e:
        print(f"[DB] Error fetching history: {e}")
        return None


# ── Emergency Assistance Mode Modules ────────────────────────────────────────

def _play_emergency_sound():
    """Plays a non-blocking siren tone using Windows winsound."""
    import winsound
    try:
        # Playing a high-low siren tone
        for _ in range(3):
            winsound.Beep(1200, 250)
            winsound.Beep(800, 250)
    except Exception as e:
        print(f"[WARN] Emergency audio alert failed: {e}")


def trigger_sound_alert():
    """Trigger the emergency sound alert in a separate background thread."""
    threading.Thread(target=_play_emergency_sound, name="EmergencySoundThread", daemon=True).start()


def save_emergency_event(detected_keyword: str, recognized_text: str,
                         translated_text: str = "", language: str = "English",
                         confidence: float = 100.0) -> bool:
    """
    Saves the emergency event details to the Supabase table `emergency_events`.
    """
    try:
        from datetime import datetime, timezone
        timestamp = datetime.now(timezone.utc).isoformat()
        
        sb = SupabaseManager()
        
        data = {
            "detected_keyword": detected_keyword,
            "recognized_text": recognized_text,
            "translated_text": translated_text,
            "language": language,
            "confidence": confidence,
            "created_at": timestamp
        }
        
        res = sb.insert("emergency_events", data)
        if res is not None:
            print("[DB] Emergency Event Saved Successfully")
            return True
        else:
            print("[DB] Save Emergency Event Failed")
            return False
    except Exception as e:
        print("[DB] Save Emergency Event Failed")
        print(f"     Error: {e}")
        return False


def get_emergency_history() -> list | None:
    """
    Fetches the latest 5 records from emergency_events table in Supabase.
    """
    try:
        sb = SupabaseManager()
        res = sb.client.table("emergency_events").select("*").order("created_at", descending=True).limit(5).execute()
        return res.data
    except Exception as e:
        print(f"[DB] Error fetching emergency history: {e}")
        return None


def print_emergency_history():
    """Fetches and prints the recent emergency events history to the console."""
    history = get_emergency_history()
    if history:
        print("\n" + "═" * 58)
        print("  EMERGENCY ASSISTANCE LOGS (Latest 5 Events)")
        print("═" * 58)
        for event in history:
            kw = event.get("detected_keyword", "N/A")
            msg = event.get("recognized_text", "N/A")
            created_at = event.get("created_at", "N/A")
            lang = event.get("language", "English")
            
            try:
                from datetime import datetime
                time_part = datetime.fromisoformat(created_at.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M:%S")
            except Exception:
                time_part = created_at
                
            print(f"[{time_part}] | Language: {lang} | Keyword: {kw}")
            print(f"  Recognized Text: {msg}")
            print("-" * 58)
        print("═" * 58 + "\n")


def get_emergency_count_today() -> int:
    """
    Queries Supabase to get the number of emergency events created today (UTC).
    """
    try:
        from datetime import datetime, timezone
        now_utc = datetime.now(timezone.utc)
        today_start = datetime(now_utc.year, now_utc.month, now_utc.day, tzinfo=timezone.utc).isoformat()
        
        sb = SupabaseManager()
        res = sb.client.table("emergency_events").select("id", count="exact").gte("created_at", today_start).execute()
        return res.count if res.count is not None else len(res.data)
    except Exception as e:
        print(f"[DB] Error getting today's emergency count: {e}")
        return 0


# ── Future-Ready Notification Hooks (Optional Modules) ────────────────────────

def send_sms_alert(keyword: str, recognized_text: str, language: str):
    """Optional future module: SMS Integration (e.g., Twilio)."""
    pass


def send_whatsapp_alert(keyword: str, recognized_text: str, language: str):
    """Optional future module: WhatsApp Business API integration."""
    pass


def send_email_alert(keyword: str, recognized_text: str, language: str):
    """Optional future module: Email Notification (SMTP / SendGrid)."""
    pass


def notify_caregiver(keyword: str, recognized_text: str, language: str):
    """Optional future module: Push Notifications to Caregiver companion app."""
    pass


def share_location():
    """Optional future module: Location Sharing (GPS / IP Geolocation)."""
    return "Lat: 13.0827, Lon: 80.2707 (Chennai, India)"


# ═══════════════════════════════════════════════════════════════════════════
# Model & Feature Extraction
# ═══════════════════════════════════════════════════════════════════════════

def load_model():
    """Load the trained MLP model, label encoder, and scaler."""
    global MODEL_EXPECTS_ENHANCED
    for path in (MODEL_PATH, ENCODER_PATH, SCALER_PATH):
        if not os.path.exists(path):
            print(f"[ERROR] Missing file: {path}")
            print("        Run train_mlp.py first to generate model artefacts.")
            sys.exit(1)

    model = joblib.load(MODEL_PATH)
    le = joblib.load(ENCODER_PATH)
    scaler = joblib.load(SCALER_PATH)

    # Determine model input dimension dynamically
    if hasattr(scaler, 'n_features_in_'):
        num_feats = scaler.n_features_in_
    elif hasattr(model, 'n_features_in_'):
        num_feats = model.n_features_in_
    else:
        num_feats = 63  # default fallback

    MODEL_EXPECTS_ENHANCED = (num_feats == 99)
    print(f"[OK] Model, encoder, and scaler loaded. Expected features: {num_feats}")
    if not MODEL_EXPECTS_ENHANCED:
        print("[WARN] Compatibility Mode Active: Loaded model expects 63 features (raw landmarks).")
        print("       Please run train_mlp.py to retrain the model with 99 enhanced features for maximum stability.")
    else:
        print("[OK] Enhanced Feature Mode Active: Using 99 normalized & engineered features.")

    return model, le, scaler


def extract_landmarks(hand_landmarks) -> np.ndarray:
    """Convert MediaPipe hand landmarks to a flat 63-element array."""
    coords = []
    for lm in hand_landmarks.landmark:
        coords.extend([lm.x, lm.y, lm.z])
    return np.array(coords, dtype=np.float32).reshape(1, -1)


# ═══════════════════════════════════════════════════════════════════════════
# HUD Drawing Utilities
# ═══════════════════════════════════════════════════════════════════════════

def draw_unicode_text(frame, text, position, color, font_size=24, thickness=1):
    """Render Unicode text (Tamil, etc.) on an OpenCV frame using PIL by cropping the local area for performance."""
    if not PIL_AVAILABLE or not text:
        cv2.putText(frame, text, position, cv2.FONT_HERSHEY_SIMPLEX,
                    font_size / 30, (180, 180, 180), thickness, cv2.LINE_AA)
        return

    try:
        h, w = frame.shape[:2]
        x, y = position
        
        # Estimate text dimensions (generous padding)
        text_h = int(font_size * 1.6)
        text_w = int(len(text) * font_size * 1.2)
        
        # Define bounding box for cropping (constrain within frame boundaries)
        x1 = max(0, x - 10)
        y1 = max(0, y - 5)
        x2 = min(w, x + text_w + 10)
        y2 = min(h, y + text_h + 5)
        
        if x2 <= x1 or y2 <= y1:
            return
            
        # Crop only the local region of interest
        roi = frame[y1:y2, x1:x2]
        
        # Render text on ROI using PIL
        pil_img = Image.fromarray(cv2.cvtColor(roi, cv2.COLOR_BGR2RGB))
        draw = ImageDraw.Draw(pil_img)
        
        font = None
        for font_path in [
            "C:/Windows/Fonts/Nirmala.ttf",
            "C:/Windows/Fonts/Latha.ttf",
            "C:/Windows/Fonts/Arial.ttf",
        ]:
            try:
                font = ImageFont.truetype(font_path, font_size)
                break
            except Exception:
                continue
        if font is None:
            font = ImageFont.load_default()
            
        # Local text position is relative to ROI origin
        local_pos = (x - x1, y - y1)
        draw.text(local_pos, text, font=font, fill=color)
        
        # Convert back and paste onto frame
        frame[y1:y2, x1:x2] = cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)
    except Exception as e:
        cv2.putText(frame, text, position, cv2.FONT_HERSHEY_SIMPLEX,
                    font_size / 30, (180, 180, 180), thickness, cv2.LINE_AA)


def check_hand_quality(hand_landmarks):
    """
    Checks if the hand landmarks meet quality criteria (Phase 7):
      - Not too close to the edge (within 2% margin)
      - Not too small (bounding box width and height >= 12% of screen)
      - Has valid coordinates (no NaNs or infinite numbers)
      - Has sufficient spread (not collapsed to a single point)
    """
    # 1. NaN and infinite check
    coords = []
    xs = []
    ys = []
    for lm in hand_landmarks.landmark:
        if not np.isfinite(lm.x) or not np.isfinite(lm.y) or not np.isfinite(lm.z):
            return False, "Invalid Coordinates"
        xs.append(lm.x)
        ys.append(lm.y)
        coords.append([lm.x, lm.y])

    # 2. Edge check
    for x, y in zip(xs, ys):
        if x < HAND_EDGE_MARGIN or x > (1.0 - HAND_EDGE_MARGIN) or y < HAND_EDGE_MARGIN or y > (1.0 - HAND_EDGE_MARGIN):
            return False, "Hand Too Close to Edge"

    # 3. Size check
    bbox_w = max(xs) - min(xs)
    bbox_h = max(ys) - min(ys)
    if bbox_w < HAND_MIN_BBOX_SIZE or bbox_h < HAND_MIN_BBOX_SIZE:
        return False, "Hand Too Small / Far"

    # 4. Spread check (standard deviation of landmarks)
    coords = np.array(coords, dtype=np.float32)
    std_dev = np.std(coords, axis=0)
    if np.any(std_dev < HAND_MIN_LANDMARK_SPREAD):
        return False, "Hand Configuration Jumbled"

    return True, "OK"


def calculate_hand_movement(current_landmarks, prev_landmarks_pts) -> float:
    """
    Calculates average 2D landmark displacement between consecutive frames (Phase 6).
    prev_landmarks_pts is a list/ndarray of shape (21, 2).
    """
    if current_landmarks is None or prev_landmarks_pts is None:
        return 0.0
    curr_pts = np.array([[lm.x, lm.y] for lm in current_landmarks.landmark], dtype=np.float32)
    prev_pts = np.array(prev_landmarks_pts, dtype=np.float32)
    if curr_pts.shape != prev_pts.shape:
        return 0.0
    distances = np.linalg.norm(curr_pts - prev_pts, axis=1)
    return float(np.mean(distances))


class AdaptiveLandmarkSmoother:
    """
    Motion-adaptive EMA landmark smoother.

    When hand is stationary → alpha = EMA_ALPHA_SLOW (smoother, reduces jitter)
    When hand is moving fast → alpha = EMA_ALPHA_FAST (near-raw, eliminates lag)

    Formula: smoothed = alpha * current + (1 - alpha) * previous
    """
    def __init__(self, alpha_slow=EMA_ALPHA_SLOW, alpha_fast=EMA_ALPHA_FAST,
                 speed_threshold=EMA_SPEED_THRESHOLD):
        self.alpha_slow = alpha_slow
        self.alpha_fast = alpha_fast
        self.speed_threshold = speed_threshold
        self.prev_landmarks = None
        self.current_alpha = alpha_fast  # Expose for debug panel

    def smooth(self, hand_landmarks):
        """
        Applies motion-adaptive EMA smoothing to landmark coordinates in-place.
        Returns the modified hand_landmarks object.
        """
        current = np.array(
            [[lm.x, lm.y, lm.z] for lm in hand_landmarks.landmark],
            dtype=np.float32
        )

        if self.prev_landmarks is None:
            self.prev_landmarks = current.copy()
            self.current_alpha = self.alpha_fast
            return hand_landmarks

        # Compute per-landmark speed (average 2D displacement)
        speed = float(np.mean(np.linalg.norm(
            current[:, :2] - self.prev_landmarks[:, :2], axis=1
        )))

        # Adaptive alpha: fast motion → high alpha (responsive), slow → low alpha (smooth)
        self.current_alpha = self.alpha_fast if speed > self.speed_threshold else self.alpha_slow

        smoothed = self.current_alpha * current + (1.0 - self.current_alpha) * self.prev_landmarks
        self.prev_landmarks = smoothed.copy()

        # Modify coordinates in place
        for i, lm in enumerate(hand_landmarks.landmark):
            lm.x = float(smoothed[i, 0])
            lm.y = float(smoothed[i, 1])
            lm.z = float(smoothed[i, 2])

        return hand_landmarks

    def reset(self):
        self.prev_landmarks = None
        self.current_alpha = self.alpha_fast


def calculate_stability_score(stability_buffer, max_variance=STABILITY_MAX_VARIANCE):
    """
    Computes a stability score from 0 to 100 based on the variance of the 21 landmarks
    over a rolling queue of the last N frames.
    """
    if len(stability_buffer) < 2:
        return 100  # Assume fully stable if we don't have enough frames yet
    
    # stability_buffer contains arrays of shape (21, 2)
    frames = np.array(list(stability_buffer), dtype=np.float32)  # Shape: (num_frames, 21, 2)
    
    # Calculate the variance of each landmark over time (axis=0)
    # Then take the mean variance across all landmarks and dimensions (x, y)
    variance = float(np.mean(np.var(frames, axis=0)))
    
    # Map variance to a 0–100 score: 0 variance = 100 score, max_variance = 0 score
    score = max(0, min(100, int(100 * (1.0 - variance / max_variance))))
    return score


def draw_rounded_rect(img, pt1, pt2, color, radius=18, thickness=-1, alpha=0.7, border_color=None, border_thickness=1, accent_color=None):
    """
    Draw a filled rounded rectangle with transparency, anti-aliased borders, and a left accent line.
    """
    overlay = img.copy()
    x1, y1 = pt1
    x2, y2 = pt2
    
    # Ensure radius is non-negative and doesn't exceed dimensions
    radius = max(0, min(radius, abs(x2 - x1) // 2, abs(y2 - y1) // 2))
    
    # Draw body
    cv2.rectangle(overlay, (x1 + radius, y1), (x2 - radius, y2), color, thickness)
    cv2.rectangle(overlay, (x1, y1 + radius), (x2, y2 - radius), color, thickness)
    
    # Draw corners
    for c in [(x1 + radius, y1 + radius, 180), (x2 - radius, y1 + radius, 270),
              (x1 + radius, y2 - radius, 90), (x2 - radius, y2 - radius, 0)]:
        cv2.ellipse(overlay, (c[0], c[1]), (radius, radius), c[2], 0, 90, color, thickness)
        
    cv2.addWeighted(overlay, alpha, img, 1.0 - alpha, 0, img)
    
    # Draw border
    if border_color is not None:
        cv2.line(img, (x1 + radius, y1), (x2 - radius, y1), border_color, border_thickness, cv2.LINE_AA)
        cv2.line(img, (x1 + radius, y2), (x2 - radius, y2), border_color, border_thickness, cv2.LINE_AA)
        cv2.line(img, (x1, y1 + radius), (x1, y2 - radius), border_color, border_thickness, cv2.LINE_AA)
        cv2.line(img, (x2, y2 - radius), (x2, y1 + radius), border_color, border_thickness, cv2.LINE_AA)
        for c in [(x1 + radius, y1 + radius, 180), (x2 - radius, y1 + radius, 270),
                  (x1 + radius, y2 - radius, 90), (x2 - radius, y2 - radius, 0)]:
            cv2.ellipse(img, (c[0], c[1]), (radius, radius), c[2], 0, 90, border_color, border_thickness, cv2.LINE_AA)
            
    # Draw accent stripe
    if accent_color is not None:
        stripe_offset = 6
        cv2.line(img, (x1 + stripe_offset, y1 + radius), (x1 + stripe_offset, y2 - radius), accent_color, 3, cv2.LINE_AA)


def draw_confidence_bar(img, x, y, w, h, confidence, color):
    """Draw a pill-shaped progress bar using anti-aliased lines."""
    if h % 2 != 0:
        h += 1
    radius = h // 2
    p1 = (x + radius, y + radius)
    p2 = (x + w - radius, y + radius)
    
    # Background line
    cv2.line(img, p1, p2, (40, 40, 50), h, cv2.LINE_AA)
    
    # Foreground line
    fill_w = int(w * confidence)
    if fill_w >= h:
        cv2.line(img, p1, (x + radius + int((w - 2 * radius) * confidence), y + radius), color, h - 2, cv2.LINE_AA)
    elif fill_w > 0:
        cv2.circle(img, p1, radius - 1, color, -1, cv2.LINE_AA)


def draw_hold_progress_bar(img, x, y, w, h, progress, color):
    """Draw a pill-shaped hold progress bar using anti-aliased lines."""
    if h % 2 != 0:
        h += 1
    radius = h // 2
    p1 = (x + radius, y + radius)
    p2 = (x + w - radius, y + radius)
    
    # Background line
    cv2.line(img, p1, p2, (30, 30, 40), h, cv2.LINE_AA)
    
    # Foreground line
    fill_w = int(w * min(progress, 1.0))
    if fill_w >= h:
        cv2.line(img, p1, (x + radius + int((w - 2 * radius) * progress), y + radius), color, h - 2, cv2.LINE_AA)
    elif fill_w > 0:
        cv2.circle(img, p1, radius - 1, color, -1, cv2.LINE_AA)


def draw_hud(frame, prediction, confidence, probabilities, label_names,
             word_buffer, sentence_buffer, fps, hand_detected, state,
             speech_status, selected_language="English", translated_text=""):
    """
    Draw a polished heads-up display overlay.

    The `state` dict provides temporal-logic feedback:
      - stable_prediction: the majority-voted prediction (or None)
      - hold_elapsed: seconds held so far (0.0 if not holding)
      - is_holding: True if currently counting down the hold timer
      - locked_until_reset: True if waiting for hand-reset
      - feedback_message: e.g. "Added A" (or None)
      - tracking_status: "ACTIVE", "LOST", or "RECOVERING"
      - stability_score: 0-100 score indicating landmark stability
      - current_emotion: active emotion from detector
      - emotion_confidence: emotion prediction confidence
      - emergency_count_today: number of emergency events logged today

    Args:
        selected_language: Current language mode ("English" or "Tamil").
        translated_text: Tamil translation of the sentence buffer (Tamil mode only).
    """
    h, w = frame.shape[:2]
    
    # Dynamic HUD scaling factor based on resolution width
    u_scale = 1.0 if w >= 1000 else 0.75
    margin = int(15 * u_scale)
    border_thickness = max(1, int(1.2 * u_scale))

    # ── Top-left: Title bar ─────────────────────────────────────────────────
    title_w = int(520 * u_scale)
    title_h = int(50 * u_scale)
    draw_rounded_rect(frame, (margin, margin), (margin + title_w, margin + title_h),
                      BG_DARK, radius=12, alpha=0.85, border_color=BORDER_COLOR,
                      border_thickness=border_thickness, accent_color=ACCENT_COLOR)
    
    cv2.putText(frame, "VISION-SPEAK ASL", (margin + int(20 * u_scale), margin + int(33 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.65 * u_scale, TEAL, max(1, int(2 * u_scale)), cv2.LINE_AA)

    # Language indicator
    lang_color = TEAL if selected_language == "English" else ORANGE
    cv2.putText(frame, f"Lang: {selected_language}", (margin + int(240 * u_scale), margin + int(32 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.48 * u_scale, lang_color, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # Speech status indicator
    if speech_status == SpeechEngine.STATUS_SPEAKING:
        status_color = ORANGE
        status_icon = ">> SPEAKING"
    elif speech_status == SpeechEngine.STATUS_COMPLETED:
        status_color = GREEN
        status_icon = "DONE"
    else:
        status_color = GRAY
        status_icon = "TTS READY"
    cv2.putText(frame, status_icon, (margin + int(390 * u_scale), margin + int(32 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.42 * u_scale, status_color, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # ── Mid-left: Debug Diagnostics Panel ──────────────────────────────────
    debug_x = margin
    debug_y = margin + title_h + int(12 * u_scale)
    debug_w = int(240 * u_scale)
    debug_h = int(220 * u_scale)
    draw_rounded_rect(frame, (debug_x, debug_y), (debug_x + debug_w, debug_y + debug_h),
                      BG_DARK, radius=12, alpha=0.85, border_color=BORDER_COLOR,
                      border_thickness=border_thickness, accent_color=PURPLE)
    
    cv2.putText(frame, "SYSTEM DIAGNOSTICS", (debug_x + int(15 * u_scale), debug_y + int(24 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, PURPLE, max(1, int(1 * u_scale)), cv2.LINE_AA)

    y_off = debug_y + int(52 * u_scale)
    # Render FPS
    cv2.putText(frame, f"FPS: {fps:.1f}", (debug_x + int(15 * u_scale), y_off),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, WHITE, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # Render Tracking Status
    tracking_status = state.get("tracking_status", "LOST")
    if tracking_status == "ACTIVE":
        track_color = GREEN
        track_label = "[● ACTIVE]"
    elif tracking_status == "RECOVERING":
        track_color = YELLOW
        track_label = "[◐ RECOVERY]"
    else:
        track_color = RED
        track_label = "[○ LOST]"
    cv2.putText(frame, f"Track: {track_label}", (debug_x + int(15 * u_scale), y_off + int(24 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, track_color, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # Render Prediction Confidence
    cv2.putText(frame, f"Conf: {confidence * 100:.1f}%", (debug_x + int(15 * u_scale), y_off + int(48 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, WHITE, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # Render Emotion Status
    emotion_str = state.get("current_emotion", "Neutral")
    emotion_conf = state.get("emotion_confidence", 0.0)
    cv2.putText(frame, f"Emotion: {emotion_str} ({emotion_conf*100:.0f}%)", (debug_x + int(15 * u_scale), y_off + int(72 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.42 * u_scale, WHITE, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # Render Stability Score
    stability_score = state.get("stability_score", 100)
    cv2.putText(frame, f"Stability: {stability_score}/100", (debug_x + int(15 * u_scale), y_off + int(96 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, WHITE, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # Render Process Time (frame processing latency)
    process_time_ms = state.get("process_time_ms", 0.0)
    avg_process_time_ms = state.get("avg_process_time_ms", 0.0)
    pt_color = GREEN if process_time_ms < 50 else (YELLOW if process_time_ms < 80 else RED)
    cv2.putText(frame, f"Latency: {process_time_ms:.1f}ms", (debug_x + int(15 * u_scale), y_off + int(120 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, pt_color, max(1, int(1 * u_scale)), cv2.LINE_AA)
    cv2.putText(frame, f"Avg: {avg_process_time_ms:.1f}ms", (debug_x + int(130 * u_scale), y_off + int(120 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.38 * u_scale, GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # Render Smoother Alpha
    smoother_alpha = state.get("smoother_alpha", 0.0)
    alpha_color = TEAL if smoother_alpha >= 0.7 else YELLOW
    cv2.putText(frame, f"EMA Alpha: {smoother_alpha:.2f}", (debug_x + int(15 * u_scale), y_off + int(144 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, alpha_color, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # ── Main prediction panel (right side) ──────────────────────────────────
    panel_w = int(280 * u_scale)
    panel_h = int(370 * u_scale)
    panel_x = w - panel_w - margin
    panel_y = margin
    draw_rounded_rect(frame, (panel_x, panel_y),
                      (panel_x + panel_w, panel_y + panel_h),
                      BG_DARK, radius=14, alpha=0.85, border_color=BORDER_COLOR,
                      border_thickness=border_thickness, accent_color=TEAL)

    if hand_detected:
        status = state.get("hand_status", "OK")
        if status != "OK":
            # Display Status (e.g., "Hand Not Ready" or "Stabilizing Hand...")
            status_text = "Stabilizing Hand..." if status == "Hand Moving" else status
            status_color = YELLOW if status == "Hand Moving" else RED
            status_size = cv2.getTextSize(status_text, cv2.FONT_HERSHEY_SIMPLEX, 0.65 * u_scale, max(1, int(2 * u_scale)))[0]
            status_x = panel_x + (panel_w - status_size[0]) // 2
            cv2.putText(frame, status_text, (status_x, panel_y + int(120 * u_scale)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.65 * u_scale, status_color, max(1, int(2 * u_scale)), cv2.LINE_AA)

            detail = state.get("hand_status_detail", "")
            if detail:
                detail_size = cv2.getTextSize(detail, cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, max(1, int(1 * u_scale)))[0]
                detail_x = panel_x + (panel_w - detail_size[0]) // 2
                cv2.putText(frame, detail, (detail_x, panel_y + int(160 * u_scale)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)
        elif prediction:
            # Determine prediction display (show raw prediction even if low confidence, but draw in RED)
            is_confident = (confidence >= CONFIDENCE_THRESHOLD)
            display_pred = prediction if prediction else ""
            
            # Prediction letter — large
            pred_color = TEAL if is_confident else RED
            letter_size = cv2.getTextSize(display_pred, cv2.FONT_HERSHEY_SIMPLEX, 3.0 * u_scale, max(1, int(4 * u_scale)))[0]
            letter_x = panel_x + (panel_w - letter_size[0]) // 2
            cv2.putText(frame, display_pred, (letter_x, panel_y + int(100 * u_scale)),
                        cv2.FONT_HERSHEY_SIMPLEX, 3.0 * u_scale, pred_color, max(1, int(4 * u_scale)), cv2.LINE_AA)

            # Confidence percentage
            conf_text = f"{confidence * 100:.1f}%"
            conf_color = GREEN if is_confident else RED
            conf_size = cv2.getTextSize(conf_text, cv2.FONT_HERSHEY_SIMPLEX, 0.75 * u_scale, max(1, int(2 * u_scale)))[0]
            conf_x = panel_x + (panel_w - conf_size[0]) // 2
            cv2.putText(frame, conf_text, (conf_x, panel_y + int(140 * u_scale)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.75 * u_scale, conf_color, max(1, int(2 * u_scale)), cv2.LINE_AA)

            # Confidence bar
            draw_confidence_bar(frame, panel_x + int(20 * u_scale), panel_y + int(155 * u_scale),
                                panel_w - int(40 * u_scale), int(14 * u_scale), confidence, conf_color)

            # ── Hold-time progress (temporal feedback) ──────────────────────────
            y_hold = panel_y + int(195 * u_scale)
            if state["is_holding"]:
                elapsed = state["hold_elapsed"]
                progress = elapsed / HOLD_TIME_REQUIRED
                hold_text = f"Hold: {elapsed:.1f} / {HOLD_TIME_REQUIRED:.1f}s"
                bar_color = GREEN if progress > 0.8 else ORANGE
                cv2.putText(frame, hold_text, (panel_x + int(15 * u_scale), y_hold),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.48 * u_scale, YELLOW, max(1, int(1 * u_scale)), cv2.LINE_AA)
                draw_hold_progress_bar(frame, panel_x + int(20 * u_scale), y_hold + int(8 * u_scale),
                                       panel_w - int(40 * u_scale), int(12 * u_scale), progress, bar_color)
                y_hold += int(35 * u_scale)
            elif state["locked_until_reset"]:
                cv2.putText(frame, "Locked (change sign/remove hand)",
                            (panel_x + int(12 * u_scale), y_hold),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.38 * u_scale, GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)
                y_hold += int(25 * u_scale)
            elif not is_confident:
                cv2.putText(frame, f"Low confidence (<{CONFIDENCE_THRESHOLD*100:.0f}%)",
                            (panel_x + int(12 * u_scale), y_hold),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.40 * u_scale, RED, max(1, int(1 * u_scale)), cv2.LINE_AA)
                y_hold += int(25 * u_scale)
            else:
                y_hold += int(10 * u_scale)

            # ── Top-3 predictions ───────────────────────────────────────────────
            top_indices = np.argsort(probabilities)[::-1][:3]
            y_offset = y_hold + int(12 * u_scale)
            cv2.putText(frame, "Top Predictions:", (panel_x + int(15 * u_scale), y_offset),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)
            y_offset += int(28 * u_scale)
            for rank, idx in enumerate(top_indices, 1):
                lbl = label_names[idx]
                prob = probabilities[idx]
                bar_color = TEAL if rank == 1 else TEAL_LIGHT
                text = f"{rank}. {lbl}"
                cv2.putText(frame, text, (panel_x + int(15 * u_scale), y_offset),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5 * u_scale, WHITE, max(1, int(1 * u_scale)), cv2.LINE_AA)
                draw_confidence_bar(frame, panel_x + int(60 * u_scale), y_offset - int(10 * u_scale),
                                    panel_w - int(90 * u_scale), int(10 * u_scale), prob, bar_color)
                pct = f"{prob * 100:.1f}%"
                cv2.putText(frame, pct, (panel_x + panel_w - int(55 * u_scale), y_offset),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.38 * u_scale, GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)
                y_offset += int(28 * u_scale)
    else:
        # No hand detected
        msg = "No Hand Detected"
        msg_size = cv2.getTextSize(msg, cv2.FONT_HERSHEY_SIMPLEX, 0.65 * u_scale, max(1, int(2 * u_scale)))[0]
        msg_x = panel_x + (panel_w - msg_size[0]) // 2
        cv2.putText(frame, msg, (msg_x, panel_y + int(120 * u_scale)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.65 * u_scale, GRAY, max(1, int(2 * u_scale)), cv2.LINE_AA)

        hint = "Show your hand"
        hint_size = cv2.getTextSize(hint, cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, max(1, int(1 * u_scale)))[0]
        hint_x = panel_x + (panel_w - hint_size[0]) // 2
        cv2.putText(frame, hint, (hint_x, panel_y + int(160 * u_scale)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45 * u_scale, GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # ── Emergency events daily counter (always visible at bottom of right panel) ──
    emergency_count = state.get("emergency_count_today", 0)
    counter_text = f"Emergency Events Today: {emergency_count}"
    cv2.putText(frame, counter_text, (panel_x + int(15 * u_scale), panel_y + panel_h - int(15 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.42 * u_scale, (80, 80, 255) if emergency_count > 0 else GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # ── Feedback banner (e.g. "Added A") ────────────────────────────────────
    if state["feedback_message"]:
        fb_text = state["feedback_message"]
        fb_size = cv2.getTextSize(fb_text, cv2.FONT_HERSHEY_SIMPLEX, 0.8 * u_scale, max(1, int(2 * u_scale)))[0]
        fb_x = (w - fb_size[0]) // 2
        fb_y = h // 2 - int(40 * u_scale)
        draw_rounded_rect(frame, (fb_x - int(20 * u_scale), fb_y - int(35 * u_scale)),
                          (fb_x + fb_size[0] + int(20 * u_scale), fb_y + int(15 * u_scale)),
                          (20, 100, 20), radius=14, alpha=0.85)
        cv2.putText(frame, fb_text, (fb_x, fb_y),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8 * u_scale, GREEN, max(1, int(2 * u_scale)), cv2.LINE_AA)

    # ── Word buffer (bottom bar - base layer for layout calculation) ─────────
    bar_h = int(58 * u_scale)
    bar_y = h - bar_h - margin
    draw_rounded_rect(frame, (margin, bar_y), (w - margin, bar_y + bar_h),
                      BG_DARK, radius=12, alpha=0.85, border_color=BORDER_COLOR,
                      border_thickness=border_thickness, accent_color=GRAY)

    cv2.putText(frame, "Word:", (margin + int(15 * u_scale), bar_y + int(36 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55 * u_scale, GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)

    word_text = "".join(word_buffer) if word_buffer else "_"
    cv2.putText(frame, word_text, (margin + int(75 * u_scale), bar_y + int(38 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.75 * u_scale, WHITE, max(1, int(2 * u_scale)), cv2.LINE_AA)

    # Controls hint (right-aligned dynamically)
    controls = "[Q]Quit [C]Clear [L]Lang [SPC]Word [BKSP]Del [ENTER]Speak"
    controls_size = cv2.getTextSize(controls, cv2.FONT_HERSHEY_SIMPLEX, 0.38 * u_scale, max(1, int(1 * u_scale)))[0]
    controls_x = w - margin - int(15 * u_scale) - controls_size[0]
    cv2.putText(frame, controls, (controls_x, bar_y + int(36 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.38 * u_scale, GRAY, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # ── Sentence buffer (second-from-bottom bar) ────────────────────────────
    sent_bar_h = int(48 * u_scale)
    sent_bar_y = bar_y - sent_bar_h - int(10 * u_scale)
    draw_rounded_rect(frame, (margin, sent_bar_y), (w - margin, sent_bar_y + sent_bar_h),
                      BG_DARK, radius=12, alpha=0.80, border_color=BORDER_COLOR,
                      border_thickness=border_thickness, accent_color=PURPLE)

    # Label changes to "English:" in Tamil mode
    sent_label = "English:" if selected_language == "Tamil" else "Sentence:"
    cv2.putText(frame, sent_label, (margin + int(15 * u_scale), sent_bar_y + int(30 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.48 * u_scale, PURPLE, max(1, int(1 * u_scale)), cv2.LINE_AA)

    sentence_text = " ".join(sentence_buffer) if sentence_buffer else "(press SPACE to finish words)"
    sent_color = WHITE if sentence_buffer else GRAY
    text_x_pos = margin + int(75 * u_scale) if selected_language == "Tamil" else margin + int(95 * u_scale)
    cv2.putText(frame, sentence_text, (text_x_pos, sent_bar_y + int(30 * u_scale)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55 * u_scale, sent_color, max(1, int(1 * u_scale)), cv2.LINE_AA)

    # ── Tamil translation bar (only visible in Tamil mode) ──────────────────
    if selected_language == "Tamil" and translated_text:
        tamil_bar_h = int(40 * u_scale)
        tamil_bar_y = sent_bar_y - tamil_bar_h - int(8 * u_scale)
        draw_rounded_rect(frame, (margin, tamil_bar_y), (w - margin, tamil_bar_y + tamil_bar_h),
                          BG_DARK, radius=12, alpha=0.80, border_color=BORDER_COLOR,
                          border_thickness=border_thickness, accent_color=ORANGE)
        cv2.putText(frame, "Tamil:", (margin + int(15 * u_scale), tamil_bar_y + int(26 * u_scale)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.48 * u_scale, ORANGE, max(1, int(1 * u_scale)), cv2.LINE_AA)
        draw_unicode_text(frame, translated_text,
                          (margin + int(75 * u_scale), tamil_bar_y + int(4 * u_scale)),
                          ORANGE, font_size=int(26 * u_scale), thickness=max(1, int(1 * u_scale)))

    # ── Emergency Pop-up Modal (drawn on top of all elements) ──────────────────
    if state.get("emergency_active", False):
        emergency_keyword = state.get("emergency_keyword", "UNKNOWN")
        emergency_time = state.get("emergency_trigger_time", time.time())
        emergency_language = state.get("emergency_language", "English")
        
        alert_w = int(480 * u_scale)
        alert_h = int(200 * u_scale)
        x1 = (w - alert_w) // 2
        y1 = (h - alert_h) // 2
        x2 = x1 + alert_w
        y2 = y1 + alert_h
        
        # Red background panel
        draw_rounded_rect(frame, (x1, y1), (x2, y2), (50, 50, 255), radius=16, alpha=0.95,
                          border_color=WHITE, border_thickness=max(1, int(2 * u_scale)))
        
        # Indicator Circle (to simulate 🔴)
        cv2.circle(frame, (x1 + int(35 * u_scale), y1 + int(40 * u_scale)), int(10 * u_scale), (0, 0, 255), -1)
        cv2.circle(frame, (x1 + int(35 * u_scale), y1 + int(40 * u_scale)), int(12 * u_scale), WHITE, 1, cv2.LINE_AA)
        
        # Title text
        cv2.putText(frame, "EMERGENCY DETECTED", (x1 + int(60 * u_scale), y1 + int(47 * u_scale)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.75 * u_scale, WHITE, max(1, int(2 * u_scale)), cv2.LINE_AA)
        
        # Details
        cv2.putText(frame, f"Detected Keyword: {emergency_keyword}", (x1 + int(30 * u_scale), y1 + int(95 * u_scale)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6 * u_scale, YELLOW, max(1, int(2 * u_scale)), cv2.LINE_AA)
        
        local_time_str = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(emergency_time))
        cv2.putText(frame, f"Timestamp: {local_time_str}", (x1 + int(30 * u_scale), y1 + int(135 * u_scale)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.52 * u_scale, WHITE, max(1, int(1 * u_scale)), cv2.LINE_AA)
        
        cv2.putText(frame, f"Language: {emergency_language}", (x1 + int(30 * u_scale), y1 + int(170 * u_scale)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.52 * u_scale, WHITE, max(1, int(1 * u_scale)), cv2.LINE_AA)


# ── Temporal Logic Engine ───────────────────────────────────────────────────

def get_majority_prediction(history, consistency_threshold):
    """
    Analyse the prediction history using majority voting.

    Returns (letter, ratio) if the most common prediction exceeds the
    consistency threshold, otherwise (None, 0.0).
    """
    if len(history) < history.maxlen:
        # Not enough history accumulated yet
        return None, 0.0

    counter = Counter(history)
    most_common_letter, count = counter.most_common(1)[0]
    ratio = count / len(history)

    if ratio >= consistency_threshold:
        return most_common_letter, ratio
    return None, ratio


# ═══════════════════════════════════════════════════════════════════════════
# Main Application Loop
# ═══════════════════════════════════════════════════════════════════════════

def main():
    print("\n" + "=" * 58)
    print("  ASL Sign Language - Live Prediction + Text-to-Speech")
    print("  Bilingual: English / Tamil  [Press L to toggle]")
    print("=" * 58)

    # ── Load model ──────────────────────────────────────────────────────────
    model, le, scaler = load_model()
    label_names = le.classes_

    # ── Initialize TTS engine (singleton) ───────────────────────────────────
    tts = SpeechEngine()

    # ── Initialize Supabase ─────────────────────────────────────────────────
    supabase = SupabaseManager()
    supabase.connect()

    # ── Initialize translation engine (bilingual support) ────────────────────
    translator = TranslationEngine(target_lang="English")

    # ── MediaPipe Hands ─────────────────────────────────────────────────────
    mp_hands = mp.solutions.hands
    mp_draw = mp.solutions.drawing_utils
    mp_styles = mp.solutions.drawing_styles

    hands = mp_hands.Hands(
        static_image_mode=MP_STATIC_IMAGE_MODE,
        max_num_hands=MP_MAX_NUM_HANDS,
        min_detection_confidence=MP_MIN_DETECTION_CONFIDENCE,
        min_tracking_confidence=MP_MIN_TRACKING_CONFIDENCE,
    )

    # ── Webcam ──────────────────────────────────────────────────────────────
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("[ERROR] Cannot open webcam.")
        sys.exit(1)

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, WEBCAM_WIDTH)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, WEBCAM_HEIGHT)

    print("[OK] Webcam opened. Press Q or ESC to quit.\n")

    # ── Language State ──────────────────────────────────────────────────────
    selected_language = "English"  # Default: "English" or "Tamil"

    # ── Hand Tracking Stability & Hysteresis State Variables ────────────────
    landmark_smoother = AdaptiveLandmarkSmoother()
    emotion_detector = EmotionDetector(detect_every_n=EMOTION_DETECT_INTERVAL)
    stability_buffer = deque(maxlen=STABILITY_BUFFER_SIZE)
    hand_missing_frames = 0
    last_valid_hand_lm = None
    tracking_status = "LOST"

    # ── State Variables (Temporal Logic) ────────────────────────────────────
    word_buffer = deque(maxlen=50)       # Current word being built letter-by-letter
    word_confidences = []                # Confidence values for characters in the current word
    sentence_buffer = []                 # Accumulated words (list of strings)
    sentence_confidences = []            # Confidence values for characters in the sentence

    # Per-frame prediction output
    current_prediction = None            # Raw prediction from model this frame
    confidence = 0.0                     # Raw confidence from model this frame
    probabilities = np.zeros(len(label_names))

    # Prediction history for majority voting (last 20 frames)
    prediction_history = deque(maxlen=HISTORY_SIZE)

    # Hold timer: tracks when a stable prediction first appeared
    hold_timer_start = None              # time.time() when hold began, None if not holding

    # Lock state: prevents re-adding the same letter
    last_added_letter = None             # The last letter successfully committed
    locked_until_reset = False           # True = waiting for hand removal or new sign

    # Feedback overlay
    feedback_message = None              # e.g. "Added A"
    feedback_timestamp = 0.0             # time.time() when feedback was set

    # ── Emergency State Variables ───────────────────────────────────────────
    emergency_active = False
    emergency_keyword = ""
    emergency_trigger_time = 0.0
    emergency_language = "English"
    last_emergency_trigger_time = 0.0
    emergency_cooldown_duration = 30.0  # 30 seconds duplicate protection
    emergency_display_duration = 5.0    # Show alert popup for at least 5 seconds
    
    # Query today's emergency count on boot (cached value incremented locally)
    print("[DB] Fetching today's emergency events count...")
    emergency_count_today = get_emergency_count_today()
    print(f"[DB] Initialized today's count: {emergency_count_today}")

    # FPS tracking
    prev_time = time.time()
    fps = 0.0

    # Performance tracking (debug panel)
    process_time_history = deque(maxlen=30)  # Rolling 30-frame average
    frame_process_time_ms = 0.0

    # Hand motion tracking
    prev_landmarks_pts = None

    print("[STATE] Temporal logic engine active:")
    print(f"        History window:   {HISTORY_SIZE} frames")
    print(f"        Consistency:      >{CONSISTENCY_THRESHOLD*100:.0f}%")
    print(f"        Confidence:       >={CONFIDENCE_THRESHOLD*100:.0f}%")
    print(f"        Hold time:        {HOLD_TIME_REQUIRED}s")
    print(f"        Auto-clear:       {AUTO_CLEAR}\n")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("[WARN] Failed to read frame, retrying...")
            continue

        frame = cv2.flip(frame, 1)  # mirror for natural interaction
        frame_start_time = time.time()  # Start frame processing timer
        
        # Submit frame to emotion detector (Optimization 4)
        if emotion_detector.enabled:
            emotion_detector.detect(frame)

        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = hands.process(rgb)

        hand_detected = False
        now = time.time()

        # ── Expire feedback message after FEEDBACK_DISPLAY_DURATION ──────
        if feedback_message and (now - feedback_timestamp) > FEEDBACK_DISPLAY_DURATION:
            feedback_message = None

        # ── Expire emergency alert after emergency_display_duration ──────
        if emergency_active and (now - emergency_trigger_time) > emergency_display_duration:
            emergency_active = False

        # ── Auto-clear sentence buffer after speech completes ────────────
        # Uses the one-shot `just_completed` flag to fire exactly once,
        # preventing repeated clears every frame during the COMPLETED window.
        if AUTO_CLEAR and tts.just_completed and sentence_buffer:
            sentence_buffer.clear()
            sentence_confidences.clear()
            print("[AUTO-CLEAR] Sentence buffer cleared after speech.")

        # ================================================================
        # HAND DETECTED / HYSTERESIS PROCESSING
        # ================================================================
        hand_lm = None
        if results.multi_hand_landmarks:
            hand_lm = results.multi_hand_landmarks[0]
            hand_missing_frames = 0
            hand_detected = True
            
            # 1. Adaptive EMA Landmark Smoothing (motion-adaptive alpha)
            hand_lm = landmark_smoother.smooth(hand_lm)
            
            # Cache the smoothed landmarks object for grace period
            last_valid_hand_lm = hand_lm
            tracking_status = "ACTIVE"
            
            # Append 2D coordinates to stability buffer (Optimization 9)
            stability_buffer.append(np.array([[lm.x, lm.y] for lm in hand_lm.landmark], dtype=np.float32))
        else:
            # Hysteresis grace period check (Optimization 3)
            if last_valid_hand_lm is not None and hand_missing_frames < HAND_MISSING_GRACE_FRAMES:
                hand_missing_frames += 1
                hand_detected = True
                hand_lm = last_valid_hand_lm
                tracking_status = "RECOVERING"
                # Do not append to stability buffer during grace period
            else:
                tracking_status = "LOST"
                hand_detected = False
                hand_lm = None
                last_valid_hand_lm = None
                landmark_smoother.reset()
                stability_buffer.clear()

        # Execute tracking status variables for HUD
        hand_status = "No Hand Detected"
        hand_status_detail = ""

        if hand_detected and hand_lm is not None:
            # Draw smoothed hand landmarks
            mp_draw.draw_landmarks(
                frame, hand_lm, mp_hands.HAND_CONNECTIONS,
                mp_styles.get_default_hand_landmarks_style(),
                mp_styles.get_default_hand_connections_style(),
            )

            # ── Step 1: Hand Quality Check (Optimization 7) ─────────────────
            quality_ok, quality_msg = check_hand_quality(hand_lm)
            
            # ── Step 2: Motion Check (Optimization 8) ───────────────────────
            is_moving = False
            movement_val = 0.0
            if prev_landmarks_pts is not None:
                movement_val = calculate_hand_movement(hand_lm, prev_landmarks_pts)
                if movement_val > MOTION_THRESHOLD:
                    is_moving = True
            # Store current landmarks for next frame motion check
            prev_landmarks_pts = [[lm.x, lm.y] for lm in hand_lm.landmark]

            if not quality_ok:
                hand_status = "Hand Not Ready"
                hand_status_detail = quality_msg
                current_prediction = None
                confidence = 0.0
                prediction_history.clear()
                hold_timer_start = None
            elif is_moving:
                hand_status = "Hand Moving"
                hand_status_detail = f"Speed: {movement_val:.3f}"
                current_prediction = None
                confidence = 0.0
                hold_timer_start = None
            else:
                hand_status = "OK"
                hand_status_detail = ""

                # Only predict on active hand track (not grace period recovery frames)
                if tracking_status == "ACTIVE":
                    # Extract features based on model expectation (Compatibility Mode)
                    if MODEL_EXPECTS_ENHANCED:
                        features = extract_enhanced_features(hand_lm).reshape(1, -1)
                    else:
                        features = extract_landmarks(hand_lm).reshape(1, -1)

                    features_scaled = scaler.transform(features)
                    current_prediction = le.inverse_transform(model.predict(features_scaled))[0]
                    probabilities = model.predict_proba(features_scaled)[0]
                    confidence = float(np.max(probabilities))

                    # ── Step 3: Confidence Filtering ─────────────────────────────
                    filtered_pred = current_prediction if confidence >= CONFIDENCE_THRESHOLD else None
                    prediction_history.append(filtered_pred)
                else:
                    # During recovery, we bypass prediction and clear hold timer to be safe,
                    # but keep the last prediction visual representation on HUD.
                    hold_timer_start = None

                # ── Step 5: Majority voting ───────────────────────────────────
                stable_prediction, consistency_ratio = get_majority_prediction(
                    prediction_history, CONSISTENCY_THRESHOLD
                )

                # ── Step 6: Temporal decision logic ──────────────────────────
                if stable_prediction is not None:
                    # Check if locked: same letter was just added
                    if locked_until_reset and stable_prediction == last_added_letter:
                        hold_timer_start = None  # don't accumulate hold time
                    elif stable_prediction != last_added_letter:
                        # NEW LETTER detected (different from the locked one)
                        locked_until_reset = False
                        if hold_timer_start is None:
                            hold_timer_start = now
                        else:
                            hold_elapsed = now - hold_timer_start
                            if hold_elapsed >= HOLD_TIME_REQUIRED:
                                # ── COMMIT THE LETTER ───────────────────────
                                word_buffer.append(stable_prediction)
                                word_confidences.append(confidence)
                                last_added_letter = stable_prediction
                                locked_until_reset = True
                                hold_timer_start = None

                                # Set feedback
                                feedback_message = f"Added: {stable_prediction}"
                                feedback_timestamp = now
                                print(f"[COMMIT] '{stable_prediction}' added. Word: {''.join(word_buffer)}")
                    else:
                        # Same letter, but not locked (first occurrence)
                        if hold_timer_start is None:
                            hold_timer_start = now
                        else:
                            hold_elapsed = now - hold_timer_start
                            if hold_elapsed >= HOLD_TIME_REQUIRED:
                                # ── COMMIT THE LETTER ───────────────────────
                                word_buffer.append(stable_prediction)
                                word_confidences.append(confidence)
                                last_added_letter = stable_prediction
                                locked_until_reset = True
                                hold_timer_start = None

                                feedback_message = f"Added: {stable_prediction}"
                                feedback_timestamp = now
                                print(f"[COMMIT] '{stable_prediction}' added. Word: {''.join(word_buffer)}")
                else:
                    hold_timer_start = None
        else:
            # No hand detected at all (and grace expired)
            hand_status = "No Hand Detected"
            hand_status_detail = ""
            current_prediction = None
            confidence = 0.0
            prediction_history.clear()
            hold_timer_start = None
            prev_landmarks_pts = None

            if locked_until_reset:
                locked_until_reset = False
                last_added_letter = None
                print("[RESET] Hand removed — lock cleared.")

        # ── Monitor Emergency Keywords ──────────────────────────────────────
        current_word_str = "".join(word_buffer).strip()
        current_sentence_str = " ".join(sentence_buffer).strip()
        
        detected_kw = is_emergency_text(current_word_str)
        if not detected_kw:
            detected_kw = is_emergency_text(current_sentence_str)
            
        if detected_kw:
            if now - last_emergency_trigger_time >= emergency_cooldown_duration:
                emergency_active = True
                emergency_keyword = detected_kw
                emergency_trigger_time = now
                emergency_language = selected_language
                last_emergency_trigger_time = now
                
                print(f"[EMERGENCY] Active! Keyword: {detected_kw}")
                
                # 1. Sound Alert (non-blocking background thread)
                trigger_sound_alert()
                
                # 2. Priority Speech (concat and speak at max volume)
                if selected_language == "Tamil":
                    text_to_translate = current_sentence_str if current_sentence_str else current_word_str
                    translated_tamil = translate_to_tamil(text_to_translate)
                    priority_text = "அவசர உதவி கோரப்பட்டுள்ளது. " + translated_tamil
                    speech_lang = "Tamil"
                    english_fallback = "Emergency assistance requested. " + text_to_translate
                else:
                    text_to_speak = current_sentence_str if current_sentence_str else current_word_str
                    priority_text = "Emergency assistance requested. " + text_to_speak
                    speech_lang = "English"
                    english_fallback = ""
                
                tts.speak(priority_text, language=speech_lang, volume=1.0, english_fallback=english_fallback)
                
                # 3. Supabase Log (non-blocking background thread)
                db_translated = translate_to_tamil(current_sentence_str) if selected_language == "Tamil" else ""
                db_thread = threading.Thread(
                    target=save_emergency_event,
                    args=(detected_kw, current_sentence_str, db_translated, selected_language, 100.0),
                    daemon=True
                )
                db_thread.start()
                
                # Increment count
                emergency_count_today += 1
                
                # 4. Print history in console (delayed print to allow write completion)
                def delayed_history():
                    time.sleep(1.5)
                    print_emergency_history()
                threading.Thread(target=delayed_history, daemon=True).start()
                
                # 5. Future hooks
                send_sms_alert(detected_kw, current_sentence_str, selected_language)
                send_whatsapp_alert(detected_kw, current_sentence_str, selected_language)
                send_email_alert(detected_kw, current_sentence_str, selected_language)
                notify_caregiver(detected_kw, current_sentence_str, selected_language)
                loc = share_location()
                print(f"[FUTURE READY] Share location: {loc}")

        # ── Get Emotion Result ──────────────────────────────────────────
        emotion_str = "Neutral"
        emotion_conf = 0.0
        if emotion_detector.enabled:
            emotion_str, emotion_conf = emotion_detector.get_emotion()

        # ── Calculate Hand Stability Score ──────────────────────────────
        stability_score = calculate_stability_score(stability_buffer)

        # ── Compute HUD state dict ──────────────────────────────────────
        hold_elapsed = 0.0
        is_holding = False
        if hold_timer_start is not None:
            hold_elapsed = now - hold_timer_start
            is_holding = True

        hud_state = {
            "stable_prediction": current_prediction,
            "hold_elapsed": hold_elapsed,
            "is_holding": is_holding,
            "locked_until_reset": locked_until_reset,
            "feedback_message": feedback_message,
            "emergency_active": emergency_active,
            "emergency_keyword": emergency_keyword,
            "emergency_trigger_time": emergency_trigger_time,
            "emergency_language": emergency_language,
            "emergency_count_today": emergency_count_today,
            "hand_status": hand_status,
            "hand_status_detail": hand_status_detail,
            "tracking_status": tracking_status,
            "stability_score": stability_score,
            "current_emotion": emotion_str,
            "emotion_confidence": emotion_conf,
            "process_time_ms": frame_process_time_ms,
            "avg_process_time_ms": float(np.mean(process_time_history)) if process_time_history else 0.0,
            "smoother_alpha": landmark_smoother.current_alpha,
        }

        # ── Frame Processing Time ───────────────────────────────────────────
        frame_process_time_ms = (time.time() - frame_start_time) * 1000.0
        process_time_history.append(frame_process_time_ms)

        # ── FPS ─────────────────────────────────────────────────────────
        fps = 0.8 * fps + 0.2 * (1.0 / max(now - prev_time, 1e-6))
        prev_time = now

        # ── Determine translated text for display (Tamil mode) ──────────
        display_translated = ""
        if selected_language == "Tamil" and sentence_buffer:
            sentence_text = " ".join(sentence_buffer)
            display_translated = translator.translate(sentence_text)

        # ── Draw HUD ────────────────────────────────────────────────────
        draw_hud(frame, current_prediction, confidence, probabilities,
                 label_names, word_buffer, sentence_buffer, fps,
                 hand_detected, hud_state, tts.status,
                 selected_language=selected_language,
                 translated_text=display_translated)

        cv2.imshow("ASL Sign Language Recognition", frame)

        # ── Key handling ────────────────────────────────────────────────
        key = cv2.waitKey(1) & 0xFF
        if key in (ord("q"), ord("Q"), 27):  # Q or ESC
            break

        elif key in (ord("c"), ord("C")):
            # Clear BOTH word buffer and sentence buffer
            word_buffer.clear()
            word_confidences.clear()
            sentence_buffer.clear()
            sentence_confidences.clear()
            last_added_letter = None
            locked_until_reset = False
            print("[CLEAR] Word + sentence buffers cleared.")

        elif key == 32:  # SPACE — finish current word and push to sentence
            current_word = "".join(word_buffer).strip()
            if current_word:
                sentence_buffer.append(current_word)
                sentence_confidences.extend(word_confidences)
                print(f"[WORD] \"{current_word}\" added to sentence. "
                      f"Sentence: {' '.join(sentence_buffer)}")
            word_buffer.clear()
            word_confidences.clear()
            last_added_letter = None
            locked_until_reset = False

        elif key in (ord("l"), ord("L")):
            # Toggle between English and Tamil
            if selected_language == "English":
                selected_language = "Tamil"
                translator.target_lang = "Tamil"
                print("[LANG] Language switched to: Tamil")
            else:
                selected_language = "English"
                translator.target_lang = "English"
                print("[LANG] Language switched to: English")
            feedback_message = f"Language: {selected_language}"
            feedback_timestamp = now

        elif key == 8:  # BACKSPACE
            if word_buffer:
                removed = word_buffer.pop()
                if word_confidences:
                    word_confidences.pop()
                print(f"[BKSP] Removed '{removed}'.")
                last_added_letter = None
                locked_until_reset = False

        elif key == 13:  # ENTER — speak the sentence
            print("[DEBUG] ENTER PRESSED")
            current_word = "".join(word_buffer).strip()
            if current_word:
                sentence_buffer.append(current_word)
                sentence_confidences.extend(word_confidences)
                word_buffer.clear()
                word_confidences.clear()

            if sentence_buffer:
                full_sentence = " ".join(sentence_buffer)
                print(f"[DEBUG] Text:\n{full_sentence}")

                if sentence_confidences:
                    avg_conf = (sum(sentence_confidences) / len(sentence_confidences)) * 100.0
                else:
                    avg_conf = 100.0
                avg_conf = round(avg_conf, 1)

                # Apply translation based on current language
                translated = translator.translate(full_sentence)
                tts_language = selected_language

                if selected_language == "Tamil":
                    speak_text = translated
                    english_fallback = full_sentence
                    if translated != full_sentence:
                        try:
                            print(f"[TAMIL] Translated: {translated}")
                        except Exception:
                            try:
                                print(f"[TAMIL] Translated: {translated.encode('utf-8', errors='replace')}")
                            except Exception:
                                pass
                    else:
                        print("[TAMIL] No translation found, speaking English.")
                else:
                    speak_text = full_sentence
                    english_fallback = ""

                spoken = tts.speak(speak_text, language=tts_language, english_fallback=english_fallback)
                print(f"[DEBUG] speak() returned:\n{spoken}")
                if spoken:
                    feedback_message = f"Speaking: {full_sentence}"
                    feedback_timestamp = now

                    # Save to Supabase with language and translation info
                    save_recognition(recognized_text=full_sentence,
                                     translated_text=translated if selected_language == "Tamil" else "",
                                     selected_language=selected_language,
                                     confidence=avg_conf)
            else:
                print("[TTS] No text available to speak.")
                feedback_message = "No text to speak"
                feedback_timestamp = now

    # ── Cleanup ─────────────────────────────────────────────────────────────
    emotion_detector.shutdown()
    tts.shutdown()
    hands.close()
    cap.release()
    cv2.destroyAllWindows()
    final_word = "".join(word_buffer) if word_buffer else "(empty)"
    final_sentence = " ".join(sentence_buffer) if sentence_buffer else "(empty)"
    print(f"\n[OK] Session ended.")
    print(f"     Final word:     {final_word}")
    print(f"     Final sentence: {final_sentence}")


if __name__ == "__main__":
    main()
