-- Run this script in the Supabase SQL Editor to create the user_profiles table

CREATE TABLE IF NOT EXISTS public.user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID NOT NULL UNIQUE,
    name TEXT NOT NULL,
    age INT,
    email TEXT UNIQUE NOT NULL,
    phone_number TEXT,
    emergency_contact TEXT,
    preferred_language TEXT DEFAULT 'English',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- Drop policies if they exist to prevent errors on rerun
DROP POLICY IF EXISTS "Allow authenticated users access to own profile" ON public.user_profiles;
DROP POLICY IF EXISTS "Allow anonymous access for service role/debugging" ON public.user_profiles;

-- Create policy for authenticated users to manage their own profiles
CREATE POLICY "Allow authenticated users access to own profile" ON public.user_profiles
    FOR ALL USING (auth.uid() = auth_user_id) WITH CHECK (auth.uid() = auth_user_id);

-- Create policy for anonymous / service role debugging access to prevent connection errors
CREATE POLICY "Allow anonymous access for service role/debugging" ON public.user_profiles
    FOR ALL USING (true) WITH CHECK (true);
