-- Run this script in the Supabase SQL Editor to create the emergency_events table

CREATE TABLE IF NOT EXISTS public.emergency_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detected_keyword TEXT NOT NULL,
    recognized_text TEXT,
    translated_text TEXT,
    language TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) if needed, or allow service_role inserts
ALTER TABLE public.emergency_events ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all inserts (or bypass RLS using the service_role key)
CREATE POLICY "Allow anonymous inserts" ON public.emergency_events
    FOR INSERT WITH CHECK (true);

-- Create policy to allow select access
CREATE POLICY "Allow anonymous selects" ON public.emergency_events
    FOR SELECT USING (true);
